export const FR = {
  nav: {
    client: "Client",
    clientDesc: "Louer un véhicule",
    agency: "Agence",
    agencyDesc: "Gérer ma flotte",
    loginBtn: "Se connecter",
    vehicles: "Véhicules",
    services: "Services",
    pricing: "Tarifs",
    aboutUs: "À propos",
  },
  registre: {
    successTitle: "Compte créé !",
    successText: "Votre compte a été créé avec succès. Redirection en cours…",
    userSpace: "Espace Utilisateur",
    title: "Créez votre compte",
    subtitle: "Rejoignez UppCar dès aujourd'hui et profitez de nos services.",
    googleBtn: "S'inscrire avec Google",
    orEmail: "ou avec votre e-mail",
    emailLabel: "Adresse e-mail",
    emailPlaceholder: "Votre e-mail",
    passLabel: "Mot de passe",
    passPlaceholder: "Mot de passe",
    confirmLabel: "Confirmer le mot de passe",
    confirmPlaceholder: "Répétez le mot de passe",
    passMismatch: "Les mots de passe ne correspondent pas",
    loading: "Création en cours...",
    submitBtn: "Créer mon compte",
    hasAccount: "Vous avez déjà un compte ?",
    loginLink: "Se Connecter.",
    errorServer: "Erreur de connexion au serveur",
  }
};
